/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PtRouteImport } from './routes/pt'
import { Route as EsRouteImport } from './routes/es'
import { Route as EnRouteImport } from './routes/en'
import { Route as IndexRouteImport } from './routes/index'

const PtRoute = PtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/es': typeof EsRoute
  '/pt': typeof PtRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/es': typeof EsRoute
  '/pt': typeof PtRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/es': typeof EsRoute
  '/pt': typeof PtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/en' | '/es' | '/pt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/en' | '/es' | '/pt'
  id: '__root__' | '/' | '/en' | '/es' | '/pt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRoute
  EsRoute: typeof EsRoute
  PtRoute: typeof PtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pt': {
      id: '/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof PtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRoute,
  EsRoute: EsRoute,
  PtRoute: PtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
